import {
  ASSIGNMENT_STATUS_VALUES,
  COURSE_STATUS_VALUES,
  DEFAULT_PICSUM_DIMENSIONS,
  DEFAULT_PICSUM_IMAGE_PROVIDER,
  SUBMISSION_STATUS_VALUES,
} from '@/features/instructor/common/constants';

export const INSTRUCTOR_DASHBOARD_STATUS_ORDER = [
  'published',
  'draft',
  'archived',
] as const;

export const INSTRUCTOR_DASHBOARD_PENDING_STATUSES = [
  'submitted',
  'resubmission_required',
] as const;

export const INSTRUCTOR_DASHBOARD_PENDING_DISPLAY_LIMIT = 10;

export const INSTRUCTOR_DASHBOARD_PENDING_FETCH_LIMIT = 200;

export const INSTRUCTOR_DASHBOARD_RECENT_SUBMISSION_DISPLAY_LIMIT = 20;

export const INSTRUCTOR_DASHBOARD_RECENT_SUBMISSION_FETCH_LIMIT = 100;

export const INSTRUCTOR_DASHBOARD_RECENT_WINDOW_DAYS = 7;

export const INSTRUCTOR_DASHBOARD_COVER_DIMENSIONS = DEFAULT_PICSUM_DIMENSIONS;

export const INSTRUCTOR_DASHBOARD_DATA_STALE_TIME_MS = 60_000;

export const INSTRUCTOR_DASHBOARD_IMAGE_PROVIDER = DEFAULT_PICSUM_IMAGE_PROVIDER;

export {
  ASSIGNMENT_STATUS_VALUES,
  COURSE_STATUS_VALUES,
  SUBMISSION_STATUS_VALUES,
};
